### ISSUE TITLE
Compiling failed with Windows 8 SDK, unless you install the DirectX SDK in addition

### ISSUE THREAD

**Issue by aspergatus** [jp9000/OBS#404]
There ist still a include of D3DX11.h, even part of the source already use D3D11.h.
Compiling failed because of D3DX11_IMAGE_INFO

**Comment by p51x** [comment]
Can somebody test this win 8.1 x64 build http://rghost.ru/60484567 ?

**Comment by jp9000** [comment]
D3DX is required for OBS1 for the sake of texture loading.  D3DX does not come with the Win8 SDK by default; it requires the DirectX SDK to use.

However, the D3DX dependency was removed in the new version, in favor of FFmpeg and other things.
