### ISSUE TITLE
"Show Cursor" in Display Capture Source seems ineffective on OSX

### ISSUE THREAD

**Issue by Byron** [jp9000/OBS#407]
When recording with the "Show Cursor" option on with a Display Capture source, the cursor doesn't actually show in the recording.

I have verified this issue still exists in a recent custom compiled version from github, my system runs OSX 10.10.1 . The same issue occurred with OBS 0.6.4 .

![screen shot 2015-01-14 at 16 40 05](https://cloud.githubusercontent.com/assets/63622/5741584/633322a4-9c0c-11e4-8632-d3b7cd42d9d3.png)

**Comment by hwdro** [comment]
You do realize you opened an issue in the wrong repo?
https://obsproject.com/forum/categories/obs-multiplatform-support.30/

**Comment by dodgepong** [comment]
This is the wrong repository. You're looking for https://github.com/jp9000/obs-studio

Issues with obs-studio should be reported on the forums, or the mantis bug tracker.

However, this is already a known issue, so there's probably nothing else that is needed at this point.

**Comment by Byron** [comment]
Oh, sorry for that, and thanks for the fast response ! I will just close this issue then.

Is there a reason mantis is preferred over the github bug tracker ? Or is it just legacy ?

**Comment by btorellALTA** [comment]
Git issues are pretty feature-lite, skimping on things like a decent permissions system, among other things.

**Comment by Byron** [comment]
Just for completeness, I am posting the respective mantis link here:

https://obsproject.com/mantis/view.php?id=103

Also I will be trying to get involved into the mantis ticket and offer my help.
